/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package csc4380jchacko1assignment4;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author admin
 */
public class GDI extends javax.swing.JFrame {

    /**
     * Creates new form GDI
     */
    public GDI() {
        initComponents();
        myinitComponents();
        
        
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jToolBar1 = new javax.swing.JToolBar();
        btnRectangle = new javax.swing.JButton();
        btnLine = new javax.swing.JButton();
        txtX1 = new javax.swing.JTextField();
        txtY1 = new javax.swing.JTextField();
        txtX2 = new javax.swing.JTextField();
        txtY2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JChacko1");
        setMinimumSize(new java.awt.Dimension(200, 250));

        jToolBar1.setRollover(true);

        btnRectangle.setText("Rectangle");
        btnRectangle.setFocusable(false);
        btnRectangle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRectangle.setMaximumSize(new java.awt.Dimension(55, 20));
        btnRectangle.setMinimumSize(new java.awt.Dimension(55, 20));
        btnRectangle.setPreferredSize(new java.awt.Dimension(55, 20));
        btnRectangle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangleActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRectangle);

        btnLine.setText("Line");
        btnLine.setFocusable(false);
        btnLine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLine.setMaximumSize(new java.awt.Dimension(50, 20));
        btnLine.setMinimumSize(new java.awt.Dimension(50, 20));
        btnLine.setPreferredSize(new java.awt.Dimension(50, 20));
        btnLine.setRequestFocusEnabled(false);
        btnLine.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLine);

        txtX1.setText("50");
        jToolBar1.add(txtX1);

        txtY1.setText("50");
        jToolBar1.add(txtY1);

        txtX2.setText("75");
        jToolBar1.add(txtX2);

        txtY2.setText("75");
        jToolBar1.add(txtY2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jMenu1.setText("File");

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void myinitComponents(){
        
        
        
        pnlCanvas = new pnlCanvasClass();
        this.setPreferredSize(new Dimension(500,500));
        this.getContentPane().add(pnlCanvas, BorderLayout.CENTER);
    
        //this.add(pnlCanvas);
        //jFrame1.getContentPane().add(pnlCanvas, new java.awt.GridBagConstraints());
        //this.getContentPane().add(pnlCanvas);
        //this.getContentPane().add(pnlCanvas);
        
        //this.add(pnlCanvas);
        //add(pnlCanvas);
        //this.getContentPane().add(pnlCanvas);
        //jFrame1.getContentPane().add(pnlCanvas);
        
        
        //setContentPane(pnlCanvas);
    }
    
    
    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void btnRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangleActionPerformed
        // TODO add your handling code here:
        Rectanglex1 = Integer.parseInt(txtX1.getText());
        Rectangley1 = Integer.parseInt(txtY1.getText());
        Rectanglex2 = Integer.parseInt(txtX2.getText());
        Rectangley2 = Integer.parseInt(txtY2.getText());
        
        pnlCanvas.repaint();
        
    }//GEN-LAST:event_btnRectangleActionPerformed

    private void btnLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineActionPerformed
        // TODO add your handling code here:
        Linex1 = Integer.parseInt(txtX1.getText());
        Liney1 = Integer.parseInt(txtY1.getText());
        Linex2 = Integer.parseInt(txtX2.getText());
        Liney2 = Integer.parseInt(txtY2.getText());
        
        pnlCanvas.repaint();
        
    }//GEN-LAST:event_btnLineActionPerformed

  
    public class pnlCanvasClass extends JPanel {

   // pnlCanvasClass() {
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   // }
    
    //class pnlCanvasClass extends JPanel{
       
     pnlCanvasClass(){
     setPreferredSize(new Dimension(200,225));
         
     setLocation(0, 25);
     setBackground(Color.cyan);
     
     setVisible(true);
     //setLayout(new BorderLayout());
     
   }
   
       @Override
       public void paintComponent(Graphics g){
           super.paintComponent(g);
           g.setColor(Color.black);
           g.drawLine(Linex1, Liney1, Linex2, Liney2);
           g.drawRect(Rectanglex1, Rectangley1, Rectanglex2, Rectangley2);
           
           
       }
       
       
}
    
    
    
    
   

    private JPanel pnlCanvas;
    public int Rectanglex1 = 50;
    public int Rectangley1 = 50;
    public int Rectanglex2 = 75;
    public int Rectangley2 = 75;
    public int Linex1 = 50;
    public int Liney1 = 50;
    public int Linex2 = 75;
    public int Liney2 = 75;
   
    
    
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLine;
    private javax.swing.JButton btnRectangle;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtY1;
    private javax.swing.JTextField txtY2;
    // End of variables declaration//GEN-END:variables
}
